/**
 * Task type configs — one object per task, built from the shared factory.
 *
 * Per §5, "the test that proves the blueprint is right: adding task #21 should
 * mean writing one config (plus a grader for workers) — nothing else." Each
 * file here is that ~15-line config. The schemas (source of truth) and graders
 * live in schemas.ts / graders.ts; these just wire them into TaskType objects.
 */
import type { TaskType } from '../../shared/contract';
import { systemPrompt, buildUserMessage } from '../prompt';
import {
  LabelParseSchema,
  DamageAssessmentSchema,
  HazmatSchema,
  CustomsInvoiceSchema,
  TamperSchema,
  ManifestSchema,
  TariffSchema,
  ExceptionRouteSchema,
  DimWeightSchema,
  PalletCheckSchema,
  AddressValidationSchema,
  CarrierSelectSchema,
  SlaRiskSchema,
  RmaSchema,
  RestrictedSchema,
  DocsCompletenessSchema,
  HandwrittenSchema,
  ConveyorIncidentSchema,
} from '../schemas';
import {
  gradeLabelParse,
  gradeDamage,
  gradeHazmat,
  gradeCustoms,
  gradeTamper,
  gradeManifest,
  gradeTariff,
  gradeExceptionRoute,
  gradeDimWeight,
  gradePallet,
  gradeAddress,
  gradeCarrier,
  gradeSla,
  gradeRma,
  gradeRestricted,
  gradeDocs,
  gradeHandwritten,
  gradeConveyor,
} from '../graders';

// Each config: id, label, icon, modality, difficulty, schema, prompt builder,
// grader, and the focus-card fields (derived from the schema).
export const TASK_TYPES: TaskType[] = [
  {
    id: 'label-parse',
    label: 'Label Parse',
    icon: '🏷️',
    modality: 'vision',
    difficulty: 1,
    outputSchema: LabelParseSchema,
    buildPrompt: async (s) => [
      { role: 'system', content: systemPrompt('shipping-label parser', LabelParseSchema) },
      await buildUserMessage(s),
    ],
    grade: (o, t) => gradeLabelParse(o, t, 1),
    focusFields: [
      { key: 'carrier', label: 'Carrier' },
      { key: 'trackingNumber', label: 'Tracking #' },
      { key: 'serviceLevel', label: 'Service' },
    ],
    humanControls: [
      { key: 'carrier', label: 'Carrier', kind: 'enum', options: ['DHL', 'UPS', 'FedEx', 'Royal Mail', 'DPD', 'Hermes', 'Yodel'] },
      { key: 'trackingNumber', label: 'Tracking #', kind: 'text' },
      { key: 'serviceLevel', label: 'Service', kind: 'enum', options: ['EXPRESS', 'GROUND', 'PRIORITY', 'STANDARD', 'NEXT DAY', 'TRACKED 24', 'ECONOMY'] },
    ],
  },
  {
    id: 'damage-assessment',
    label: 'Damage Assess',
    icon: '📦',
    modality: 'vision',
    difficulty: 2,
    outputSchema: DamageAssessmentSchema,
    buildPrompt: async (s) => [
      { role: 'system', content: systemPrompt('parcel damage assessor', DamageAssessmentSchema) },
      await buildUserMessage(s),
    ],
    grade: (o, t) => gradeDamage(o, t, 2),
    focusFields: [
      { key: 'damageType', label: 'Damage' },
      { key: 'severity', label: 'Severity' },
      { key: 'action', label: 'Action' },
    ],
    humanControls: [
      { key: 'damageType', label: 'Damage', kind: 'enum', options: ['crushed', 'wet', 'torn', 'none'] },
      { key: 'severity', label: 'Severity (0-5)', kind: 'number' },
      { key: 'action', label: 'Action', kind: 'enum', options: ['accept', 'repackage', 'refuse'] },
    ],
  },
  {
    id: 'hazmat-detection',
    label: 'Hazmat Check',
    icon: '☣️',
    modality: 'vision',
    difficulty: 3,
    outputSchema: HazmatSchema,
    buildPrompt: async (s) => [
      { role: 'system', content: systemPrompt('hazmat label inspector', HazmatSchema) },
      await buildUserMessage(s),
    ],
    grade: (o, t) => gradeHazmat(o, t, 3),
    focusFields: [
      { key: 'unClass', label: 'UN class' },
      { key: 'labelMissing', label: 'Label' },
      { key: 'compliant', label: 'Compliant' },
    ],
    humanControls: [
      { key: 'unClass', label: 'UN class', kind: 'text' },
      { key: 'labelMissing', label: 'Label missing?', kind: 'boolean' },
      { key: 'compliant', label: 'Compliant?', kind: 'boolean' },
    ],
  },
  {
    id: 'customs-invoice',
    label: 'Customs Invoice',
    icon: '🧾',
    modality: 'document',
    difficulty: 2,
    outputSchema: CustomsInvoiceSchema,
    buildPrompt: async (s) => [
      { role: 'system', content: systemPrompt('customs invoice extractor', CustomsInvoiceSchema) },
      await buildUserMessage(s),
    ],
    grade: (o, t) => gradeCustoms(o, t, 2),
    focusFields: [
      { key: 'hsCode', label: 'HS code' },
      { key: 'declaredValue', label: 'Value' },
      { key: 'countryOfOrigin', label: 'Origin' },
    ],
    humanControls: [
      { key: 'hsCode', label: 'HS code', kind: 'text' },
      { key: 'declaredValue', label: 'Value', kind: 'text' },
      { key: 'countryOfOrigin', label: 'Origin', kind: 'text' },
    ],
  },
  {
    id: 'seal-tamper',
    label: 'Seal / Tamper',
    icon: '🔒',
    modality: 'vision',
    difficulty: 3,
    outputSchema: TamperSchema,
    buildPrompt: async (s) => [
      { role: 'system', content: systemPrompt('container seal inspector', TamperSchema) },
      await buildUserMessage(s),
    ],
    grade: (o, t) => gradeTamper(o, t, 3),
    focusFields: [
      { key: 'sealIntact', label: 'Seal' },
      { key: 'tampered', label: 'Match' },
      { key: 'flag', label: 'Flag' },
    ],
    humanControls: [
      { key: 'sealIntact', label: 'Seal intact?', kind: 'boolean' },
      { key: 'tampered', label: 'Tampered?', kind: 'boolean' },
      { key: 'flag', label: 'Flag', kind: 'enum', options: ['clear', 'tamper', 'unknown'] },
    ],
  },
  {
    id: 'manifest-recon',
    label: 'Manifest Recon',
    icon: '📋',
    modality: 'document',
    difficulty: 1,
    outputSchema: ManifestSchema,
    buildPrompt: async (s) => [
      { role: 'system', content: systemPrompt('manifest reconciliation clerk', ManifestSchema) },
      await buildUserMessage(s),
    ],
    grade: (o, t) => gradeManifest(o, t, 1),
    focusFields: [
      { key: 'expected', label: 'Expected' },
      { key: 'scanned', label: 'Scanned' },
      { key: 'missing', label: 'Missing' },
    ],
    humanControls: [
      { key: 'expected', label: 'Expected', kind: 'number' },
      { key: 'scanned', label: 'Scanned', kind: 'number' },
      { key: 'missing', label: 'Missing', kind: 'number' },
    ],
  },
  {
    id: 'tariff-classification',
    label: 'Tariff Class',
    icon: '🌐',
    modality: 'text',
    difficulty: 2,
    outputSchema: TariffSchema,
    buildPrompt: async (s) => [
      { role: 'system', content: systemPrompt('HS tariff classifier', TariffSchema) },
      await buildUserMessage(s),
    ],
    grade: (o, t) => gradeTariff(o, t, 2),
    focusFields: [
      { key: 'hsCode', label: 'HS code' },
      { key: 'dutyCategory', label: 'Duty' },
    ],
    humanControls: [
      { key: 'hsCode', label: 'HS code', kind: 'text' },
      { key: 'dutyCategory', label: 'Duty', kind: 'enum', options: ['duty-free', 'low-duty', 'standard', 'high-duty'] },
    ],
  },
  {
    id: 'exception-routing',
    label: 'Exception Route',
    icon: '🚦',
    modality: 'text',
    difficulty: 1,
    outputSchema: ExceptionRouteSchema,
    buildPrompt: async (s) => [
      { role: 'system', content: systemPrompt('exception routing dispatcher', ExceptionRouteSchema) },
      await buildUserMessage(s),
    ],
    grade: (o, t) => gradeExceptionRoute(o, t, 1),
    focusFields: [
      { key: 'category', label: 'Category' },
      { key: 'queue', label: 'Queue' },
      { key: 'priority', label: 'Priority' },
    ],
    humanControls: [
      { key: 'category', label: 'Category', kind: 'text' },
      { key: 'queue', label: 'Queue', kind: 'text' },
      { key: 'priority', label: 'Priority', kind: 'enum', options: ['P1', 'P2', 'P3'] },
    ],
  },
  {
    id: 'dim-weight',
    label: 'Dim/Weight',
    icon: '📐',
    modality: 'vision',
    difficulty: 2,
    outputSchema: DimWeightSchema,
    buildPrompt: async (s) => [
      { role: 'system', content: systemPrompt('dimensional weight auditor', DimWeightSchema) },
      await buildUserMessage(s),
    ],
    grade: (o, t) => gradeDimWeight(o, t, 2),
    focusFields: [
      { key: 'declaredWeightKg', label: 'Weight' },
      { key: 'declaredHeightCm', label: 'Height' },
      { key: 'mismatch', label: 'Mismatch' },
    ],
    humanControls: [
      { key: 'declaredWeightKg', label: 'Weight (kg)', kind: 'number' },
      { key: 'declaredHeightCm', label: 'Height (cm)', kind: 'number' },
      { key: 'mismatch', label: 'Mismatch?', kind: 'boolean' },
    ],
  },
  {
    id: 'pallet-check',
    label: 'Pallet Check',
    icon: '🧱',
    modality: 'vision',
    difficulty: 2,
    outputSchema: PalletCheckSchema,
    buildPrompt: async (s) => [
      { role: 'system', content: systemPrompt('pallet load inspector', PalletCheckSchema) },
      await buildUserMessage(s),
    ],
    grade: (o, t) => gradePallet(o, t, 2),
    focusFields: [
      { key: 'cartonCount', label: 'Cartons' },
      { key: 'overhang', label: 'Overhang' },
      { key: 'stackingViolation', label: 'Stacking' },
    ],
    humanControls: [
      { key: 'cartonCount', label: 'Carton count', kind: 'number' },
      { key: 'overhang', label: 'Overhang?', kind: 'boolean' },
      { key: 'stackingViolation', label: 'Stacking violation?', kind: 'boolean' },
    ],
  },
  {
    id: 'address-validation',
    label: 'Address Check',
    icon: '📍',
    modality: 'text',
    difficulty: 1,
    outputSchema: AddressValidationSchema,
    buildPrompt: async (s) => [
      { role: 'system', content: systemPrompt('address validation clerk', AddressValidationSchema) },
      await buildUserMessage(s),
    ],
    grade: (o, t) => gradeAddress(o, t, 1),
    focusFields: [
      { key: 'deliverable', label: 'Status' },
      { key: 'zone', label: 'Zone' },
      { key: 'canonical', label: 'Canonical' },
    ],
    humanControls: [
      { key: 'deliverable', label: 'Deliverable?', kind: 'boolean' },
      { key: 'zone', label: 'Zone', kind: 'text' },
      { key: 'canonical', label: 'Canonical address', kind: 'text' },
    ],
  },
  {
    id: 'carrier-select',
    label: 'Carrier Select',
    icon: '🚚',
    modality: 'text',
    difficulty: 1,
    outputSchema: CarrierSelectSchema,
    buildPrompt: async (s) => [
      { role: 'system', content: systemPrompt('least-cost carrier selector', CarrierSelectSchema) },
      await buildUserMessage(s),
    ],
    grade: (o, t) => gradeCarrier(o, t, 1),
    focusFields: [
      { key: 'carrier', label: 'Carrier' },
      { key: 'service', label: 'Service' },
      { key: 'cost', label: 'Cost' },
    ],
    humanControls: [
      { key: 'carrier', label: 'Carrier', kind: 'enum', options: ['UPS', 'FedEx', 'DHL', 'Royal Mail', 'Hermes', 'Yodel'] },
      { key: 'service', label: 'Service', kind: 'text' },
      { key: 'cost', label: 'Cost', kind: 'text' },
    ],
  },
  {
    id: 'sla-risk',
    label: 'SLA / ETA',
    icon: '⏱️',
    modality: 'text',
    difficulty: 2,
    outputSchema: SlaRiskSchema,
    buildPrompt: async (s) => [
      { role: 'system', content: systemPrompt('SLA and ETA risk analyst', SlaRiskSchema) },
      await buildUserMessage(s),
    ],
    grade: (o, t) => gradeSla(o, t, 2),
    focusFields: [
      { key: 'status', label: 'Status' },
      { key: 'etaHours', label: 'ETA' },
      { key: 'cause', label: 'Cause' },
    ],
    humanControls: [
      { key: 'status', label: 'Status', kind: 'enum', options: ['on-time', 'at-risk', 'breached'] },
      { key: 'etaHours', label: 'ETA (hours)', kind: 'number' },
      { key: 'cause', label: 'Cause', kind: 'text' },
    ],
  },
  {
    id: 'rma-disposition',
    label: 'RMA / Return',
    icon: '↩️',
    modality: 'text',
    difficulty: 2,
    outputSchema: RmaSchema,
    buildPrompt: async (s) => [
      { role: 'system', content: systemPrompt('returns disposition agent', RmaSchema) },
      await buildUserMessage(s),
    ],
    grade: (o, t) => gradeRma(o, t, 2),
    focusFields: [
      { key: 'disposition', label: 'Disposition' },
      { key: 'reason', label: 'Reason' },
    ],
    humanControls: [
      { key: 'disposition', label: 'Disposition', kind: 'enum', options: ['restock', 'refurbish', 'scrap'] },
      { key: 'reason', label: 'Reason', kind: 'text' },
    ],
  },
  {
    id: 'restricted-screening',
    label: 'Restricted',
    icon: '🛑',
    modality: 'text',
    difficulty: 3,
    outputSchema: RestrictedSchema,
    buildPrompt: async (s) => [
      { role: 'system', content: systemPrompt('restricted goods screening officer', RestrictedSchema) },
      await buildUserMessage(s),
    ],
    grade: (o, t) => gradeRestricted(o, t, 3),
    focusFields: [
      { key: 'status', label: 'Status' },
      { key: 'reason', label: 'Reason' },
    ],
    humanControls: [
      { key: 'status', label: 'Status', kind: 'enum', options: ['allowed', 'restricted', 'prohibited'] },
      { key: 'reason', label: 'Reason', kind: 'text' },
    ],
  },
  {
    id: 'docs-completeness',
    label: 'Docs Check',
    icon: '📄',
    modality: 'document',
    difficulty: 1,
    outputSchema: DocsCompletenessSchema,
    buildPrompt: async (s) => [
      { role: 'system', content: systemPrompt('shipping documents completeness checker', DocsCompletenessSchema) },
      await buildUserMessage(s),
    ],
    grade: (o, t) => gradeDocs(o, t, 1),
    focusFields: [
      { key: 'bolPresent', label: 'BOL' },
      { key: 'cooPresent', label: 'COO' },
      { key: 'complete', label: 'Complete' },
    ],
    humanControls: [
      { key: 'bolPresent', label: 'BOL present?', kind: 'boolean' },
      { key: 'cooPresent', label: 'COO present?', kind: 'boolean' },
      { key: 'complete', label: 'Complete?', kind: 'boolean' },
    ],
  },
  {
    id: 'handwritten-label',
    label: 'Handwritten',
    icon: '✍️',
    modality: 'vision',
    difficulty: 3,
    outputSchema: HandwrittenSchema,
    buildPrompt: async (s) => [
      { role: 'system', content: systemPrompt('handwritten label transcriber', HandwrittenSchema) },
      await buildUserMessage(s),
    ],
    grade: (o, t) => gradeHandwritten(o, t, 3),
    focusFields: [
      { key: 'name', label: 'Name' },
      { key: 'addressLine', label: 'Address' },
      { key: 'postcode', label: 'Postcode' },
    ],
    humanControls: [
      { key: 'name', label: 'Name', kind: 'text' },
      { key: 'addressLine', label: 'Address line', kind: 'text' },
      { key: 'postcode', label: 'Postcode', kind: 'text' },
    ],
  },
  {
    id: 'conveyor-incident',
    label: 'Conveyor Cam',
    icon: '🎞️',
    modality: 'video',
    difficulty: 3,
    outputSchema: ConveyorIncidentSchema,
    buildPrompt: async (s) => [
      { role: 'system', content: systemPrompt('conveyor line-camera incident analyst', ConveyorIncidentSchema) },
      await buildUserMessage(s),
    ],
    grade: (o, t) => gradeConveyor(o, t, 3),
    focusFields: [
      { key: 'event', label: 'Incident' },
      { key: 'action', label: 'Action' },
    ],
    humanControls: [
      { key: 'event', label: 'Incident', kind: 'enum', options: ['clear', 'jam', 'fall', 'crush'] },
      { key: 'action', label: 'Action', kind: 'enum', options: ['accept', 'reroute', 'refuse'] },
    ],
  },
];
