/**
 * Docs generator — emits the Task Catalog reference page for the Docusaurus site
 * from the SINGLE SOURCE OF TRUTH (the task registry, the Zod output schemas, the
 * agent roster, and the scenario pool). Run it whenever a task, schema, or the
 * scenario pool changes so the docs can't drift:
 *
 *   npm run gen:docs
 *
 * Output: docs/docs/reference/task-catalog.md (generated — do not hand-edit).
 */
import { readFileSync, existsSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { z } from 'zod';
import { allTaskTypes } from '../src/tasks/registry';
import { AGENT_ROSTER } from '../src/data/agentRoster';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const SCEN_DIR = resolve(ROOT, 'data', 'scenarios');
const OUT = resolve(ROOT, 'docs', 'docs', 'reference', 'task-catalog.md');

/** Unwrap optional/nullable to the inner Zod type. */
function unwrap(s: z.ZodType<unknown>): z.ZodType<unknown> {
  let cur: z.ZodType<unknown> = s;
  while (cur instanceof z.ZodOptional || cur instanceof z.ZodNullable) cur = (cur as any).unwrap();
  return cur;
}

/** A readable type label for a schema field (enums list their options). */
function fieldType(s: z.ZodType<unknown>): string {
  const inner = unwrap(s);
  if (inner instanceof z.ZodEnum) return (inner as z.ZodEnum<any>).options.map((o: string) => `\`${o}\``).join(' \\| ');
  if (inner instanceof z.ZodNumber) return 'number';
  if (inner instanceof z.ZodBoolean) return 'boolean';
  if (inner instanceof z.ZodArray) return `${fieldType((inner as z.ZodArray<any>).element)}[]`;
  return 'string';
}

/** Field rows from a task's output schema (the structured object the worker emits). */
function schemaFields(schema: z.ZodType<unknown>): Array<{ key: string; type: string; optional: boolean }> {
  if (!(schema instanceof z.ZodObject)) return [];
  const shape = (schema as z.ZodObject<any>).shape as Record<string, z.ZodType<unknown>>;
  return Object.entries(shape).map(([key, v]) => ({
    key,
    type: fieldType(v),
    optional: v instanceof z.ZodOptional || v instanceof z.ZodNullable,
  }));
}

interface Scenario {
  id: string;
  difficulty: number;
  adversarial?: boolean;
  blurb?: string;
  groundTruth: Record<string, unknown>;
  input: { text?: string; imageUrl?: string; documents?: string[] };
}

function loadScenarios(taskId: string): Scenario[] {
  const f = resolve(SCEN_DIR, `${taskId}.json`);
  if (!existsSync(f)) return [];
  try {
    const arr = JSON.parse(readFileSync(f, 'utf8'));
    return Array.isArray(arr) ? arr : [];
  } catch {
    return [];
  }
}

const tasks = allTaskTypes();
const MODALITY_LABEL: Record<string, string> = { vision: 'Vision', document: 'Document', text: 'Text', video: 'Video' };
const COUNT_WORD = ['zero', 'one', 'two', 'three', 'four', 'five', 'six'];

const lines: string[] = [];
lines.push('---');
lines.push('sidebar_position: 1');
lines.push('---');
lines.push('');
lines.push('{/* GENERATED by scripts/gen-docs.ts — run `npm run gen:docs`. Do not hand-edit. */}');
lines.push('');
lines.push('# Task Catalog');
lines.push('');
lines.push(
  `Every parcel runs through a coordinated **agent graph** rather than a single call. The ` +
    `Router classifies the incoming parcel and dispatches it to one of the **${tasks.length} worker ` +
    `specialists** below; the Verifier checks the worker's output and can bounce it back; the ` +
    `Exceptions Specialist makes the final call on high-stakes or low-confidence items. See ` +
    `[the multi-agent pipeline](../concepts/multi-agent-pipeline.md) for how the roles fit together.`,
);
lines.push('');
lines.push(
  `Each task's **output schema is the single source of truth** (the Zod schema in \`src/tasks/schemas.ts\`), ` +
    `from which the prompt instruction, the tolerant parser, the grader's field list, and the focus-card ` +
    `rows all derive. This page is generated from that registry + the scenario pool.`,
);
lines.push('');

// --- the four roles ---
lines.push('## The agent roles');
lines.push('');
lines.push('| | Role | Step | What it does |');
lines.push('|---|---|---|---|');
for (const r of AGENT_ROSTER) {
  lines.push(`| ${r.icon} | **${r.name}** | ${r.stepId} | ${r.job} |`);
}
lines.push('');

// --- the task overview table ---
const total = tasks.reduce((n, t) => n + loadScenarios(t.id).length, 0);
const modalityCount = new Set(tasks.map((t) => t.modality)).size;
lines.push('## Worker specialists');
lines.push('');
lines.push(`**${tasks.length} task types · ${total} scenarios**, spread across all ${COUNT_WORD[modalityCount] ?? modalityCount} modalities.`);
lines.push('');
lines.push('| | Task | `id` | Modality | Difficulty | Scenarios |');
lines.push('|---|---|---|---|---|---|');
for (const t of tasks) {
  const n = loadScenarios(t.id).length;
  lines.push(`| ${t.icon} | ${t.label} | \`${t.id}\` | ${MODALITY_LABEL[t.modality] ?? t.modality} | ${t.difficulty} | ${n} |`);
}
lines.push('');

// --- per-task detail ---
lines.push('## Task details');
lines.push('');
for (const t of tasks) {
  const scenarios = loadScenarios(t.id);
  const fields = schemaFields(t.outputSchema);
  const example = scenarios.find((s) => s.adversarial) ?? scenarios[0];

  lines.push(`### ${t.icon} ${t.label}`);
  lines.push('');
  lines.push(
    `\`${t.id}\` · **${MODALITY_LABEL[t.modality] ?? t.modality}** · difficulty ${t.difficulty} · ` +
      `${scenarios.length} scenario${scenarios.length === 1 ? '' : 's'}`,
  );
  lines.push('');
  if (fields.length) {
    lines.push('Output schema (the structured object the worker must emit, graded against ground truth):');
    lines.push('');
    lines.push('| Field | Type |');
    lines.push('|---|---|');
    for (const f of fields) lines.push(`| \`${f.key}\`${f.optional ? ' _(optional)_' : ''} | ${f.type} |`);
    lines.push('');
  }
  if (example) {
    lines.push(`Example scenario — \`${example.id}\`${example.adversarial ? ' ⚠ adversarial' : ''}${example.blurb ? ` (${example.blurb})` : ''}:`);
    lines.push('');
    lines.push('```json');
    lines.push(JSON.stringify(example.groundTruth, null, 2));
    lines.push('```');
    lines.push('');
  }
}

lines.push('---');
lines.push('');
lines.push(
  'Adding a task #18+ is one config plus a grader — see [Add a Task](../extending/add-a-task.md) and ' +
    '[Authoring scenario data](../extending/data.md). Re-run `npm run gen:docs` to refresh this page.',
);
lines.push('');

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, lines.join('\n'), 'utf8');
console.log(`✓ wrote ${OUT} (${tasks.length} tasks, ${total} scenarios)`);
